version: '3.3'
services:
  elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
      environment:
        - bootstrap.memory_lock=true
        - cluster.name=es-cluster
        - discovery.type=single-node
        - cluster.routing.allocation.disk.threshold_enabled=false
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - xpack.monitoring.enabled=true
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      ulimits:
        memlock:
          soft: -1
          hard: -1
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.apm.enabled=false
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm-server:
    container_name: apm
    image: docker.elastic.co/apm/apm-server:7.17.1
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - "8200:8200"
    depends_on:
      - kibana
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]

volumes:
  esdata:
    driver: local
  kibana_data:
    driver: local
